# This is a basic workflow to help you get started with Actions

name: notion-article-review

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  schedule:
    - cron: '0 4 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # query articles in notion database
  article-query:
    uses: ./.github/workflows/notion-article-query.yml
    secrets: inherit
    

  # This workflow contains a single job called "article-review"
  article-review:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs: article-query
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
    
      - name: Cache
        id: article-cache
        uses: actions/cache@v3.0.2
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: index.html
          # An explicit key for restoring and saving the cache
          key: article
          
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
      - name: send mail
        uses: dawidd6/action-send-mail@master
        with:
          # Required mail server address:
          server_address: smtp.163.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Notion文章阅读回顾-${{ steps.date.outputs.date }}
          # Required recipients' addresses:
          to: ${{secrets.MAIL_TO}}
          # Required sender full name (address can be skipped):
          from: Github NotionReview
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
#           body: ${{ needs.article-query.outputs.article-item }}
          # Optional HTML body read from file:
          html_body: ${{ needs.article-query.outputs.article-item }}
          # Optional converting Markdown to HTML (set content_type to text/html too):
#           convert_markdown: true
    
