# This is a basic workflow to help you get started with Actions

name: notion-article-review

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  schedule:
    - cron: '0 4 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # query articles in notion database
  article-query:
    uses: ./.github/workflows/notion-article-query.yml
    secrets: inherit
    

  # This workflow contains a single job called "article-review"
  article-review:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
    
#       - name: query articles in notion database
#         uses: ./.github/workflows/notion-article-query.yml
      
      - name: send mail
        uses: dawidd6/action-send-mail@master
        with:
          # Required mail server address:
          server_address: smtp.163.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Notion文章阅读回顾
          # Required recipients' addresses:
          to: ${{secrets.MAIL_TO}}
          # Required sender full name (address can be skipped):
          from: Github NotionReview
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
#           body: Build job of ${{github.repository}} completed successfully!
          # Optional HTML body read from file:
          html_body: file://index.html
          # Optional converting Markdown to HTML (set content_type to text/html too):
#           convert_markdown: true
    needs: article-query
