# This is a basic workflow to help you get started with Actions

name: notion-article-query

# Controls when the workflow will run
on:
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  query-article:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          
      - name: Query Notion Articles
        run: npm install && npm run server
        env: 
          # Required mail server address:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          # Required mail server port:
          DATABASE_ID: ${{ secrets.ARTICLE_DATABASE_ID }}
          
      - name: cache article content for sharing among jobs
        uses: actions/cache@v3.0.2
        with: 
          # A list of files, directories, and wildcard patterns to cache and restore
          path: index.html
          # An explicit key for restoring and saving the cache
          key: article
